model:
  vocab_size: 0
  max_seq_len: 0
  n_layer: 0
  d_model: 0
  n_head: 0
  d_ffn: 0
  dropout: 0.0
  bias: false
  attention:
    positional_embedding: "RoPE" #"learnable_positional_embedding"
    dropout: 0.0
    RoPE:
      base: 10000

init:
  linear:
    weight:
      method: "normal"
      std: 0.02
    bias:
      method: "zeros"
  embedding:
    method: "normal"
    std: 0.02
  layer_norm:
    alpha:
      method: "ones"
    beta:
      method: "zeros"
  attention:
    qkv_linear:
      weight:
        method: "normal"
        std: 0.02
      bias:
        method: "zeros"
    out_linear:
      weight:
        method: "normal"
        std: 0.02
      bias:
        method: "zeros"